### ISSUE TITLE
Feature: `toValidator` variant of `toPlutusScript` which checks that scripts are fully applied?

### ISSUE THREAD

**Issue by zmrocze** [mlabs-haskell/ply-ctl#1]
Hey, 
it seems like `toPlutusScript` function is supposed to always be called at some point, to make practical use of the script with ctl? Right, or have I missed some other casting function?

Surely at some point the script type information needs to be forgotten, to use scripts with untyped ctl interfaces. But I'd hope there to be functions `toValidator`/`toMintingPolicy` which in smart-constructor style forget the type info, but assuring that provided script was already fully applied and that it's of the expected type (validator/minting policy). Because without it there is no additional type safety really.

**Comment by klntsky** [comment]
> but assuring that provided script was already fully applied

Do you have any idea how to check that?

**Comment by zmrocze** [comment]
@klntsky just in case: this is ply-ctl

**Comment by zmrocze** [comment]
```
toValidator :: TypedScript ValidatorRole Nil -> Validator
toValidator = toPlutusScript >>> Validator

toMintingPolicy :: TypedScript MintingPolicyRole Nil -> MintingPolicy
toMintingPolicy = toPlutusScript >>> PlutusMintingPolicy
```
@SeungheonOh, @klntsky How would you feel if i'd pr those two into the Types module?

**Comment by SeungheonOh** [comment]
Looks good

**Comment by SeungheonOh** [comment]
Looks good to me. Pretty sure we have that on ply too

**Comment by zmrocze** [comment]
@SeungheonOh Did^
